export const GET_USER = 'GET_USER';
export const DISPLAY_MACHINE_NUMBERS = 'DISPLAY_MACHINE_NUMBERS'
export const GET_SPIN_NUMBER = 'GET_SPIN_NUMBER';
export const DISPLAY_BINGO_CARD_NUMBERS = 'DISPLAY_BINGO_CARD_NUMBERS';
export const DISPLAY_EACH_BINGO_CARD_NUMBERS = 'DISPLAY_EACH_BINGO_CARD_NUMBERS';